# Generated by Django 4.2.11 on 2024-03-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lid_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
