# Generated by Django 4.2.11 on 2024-03-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lid_app', '0003_alter_postimage_options_postimage_created_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lid',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='lid',
            name='tg_id',
            field=models.CharField(default='1234567', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
