# Generated by Django 4.2.11 on 2024-03-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lid_app', '0004_alter_lid_options_lid_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='name',
            field=models.CharField(default='post', max_length=10),
        ),
    ]
